import {
  FeeValueType,
  ProviderFeatureType,
  ProviderFeeType,
  ProviderProsConsType,
  ProviderSourceType,
  ProviderType,
  VerificationStatus,
} from "@prisma/client";

export const BtcMarkets = {
  name: "BTC Markets",
  slug: "btc-markets",
  website: "https://www.btcmarkets.net",
  description:
    "Australian cryptocurrency exchange offering Advanced Trade/order-book markets and Quick Buy/Sell, with AUD funding, mobile trading and API access.",
  providerType: ProviderType.CRYPTO_EXCHANGE,
  jurisdictions: ["AU"],
  verificationStatus: VerificationStatus.VERIFIED,
  lastVerifiedAt: new Date("2026-09-17"),
  assetSymbols: ["BTC", "ETH", "SOL", "XRP"],
  logo: "/images/providers/btc-markets.svg",
  facts: [
    {
      label: "Headquarters / Market",
      value: "Australia",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "AUD Support",
      value: "Yes",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Platform Type",
      value: "Centralised cryptocurrency exchange",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Trading interfaces",
      value: "Advanced Trade/order book and Quick Buy/Sell",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  fees: [
    {
      feeType: ProviderFeeType.TRADING,
      label: "AUD/USDT exchange trading fee",
      valueType: FeeValueType.TIERED,
      percentage: 0.85,
      displayValue:
        "0.85% at the lowest volume tier, decreasing to 0.10% above $5m rolling 30-day volume",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.MAKER,
      label: "BTC-pair maker fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: -0.05,
      displayValue: "-0.05% maker rebate for supported BTC market pairs",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.TAKER,
      label: "BTC-pair taker fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 0.2,
      displayValue: "0.20% for supported BTC market pairs",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.SPREAD,
      label: "Quick Buy/Sell spread",
      valueType: FeeValueType.VARIABLE,
      displayValue:
        "Variable spread included in quoted price; no additional Quick Buy/Sell trading fee",
      jurisdiction: "AU",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  features: [
    {
      featureType: ProviderFeatureType.AUD_DEPOSITS,
      available: true,
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.MOBILE_APP,
      available: true,
      sourceUrl: "https://www.btcmarkets.net",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.API_ACCESS,
      available: true,
      sourceUrl: "https://docs.btcmarkets.net/",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.TWO_FACTOR_AUTH,
      available: true,
      sourceUrl: "https://www.btcmarkets.net",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.COLD_STORAGE,
      available: true,
      sourceUrl: "https://www.btcmarkets.net/institutional",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  prosCons: [
    {
      type: ProviderProsConsType.PRO,
      label:
        "Offers Advanced Trade/order-book trading plus simpler Quick Buy/Sell pricing",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label: "Lowest-volume AUD/USDT exchange trading tier is 0.85%",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label:
        "Quick Buy/Sell pricing includes a variable spread rather than using the Advanced Trade fee schedule",
      sourceUrl: "https://www.btcmarkets.net/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  sources: [
    {
      label: "Official website",
      url: "https://www.btcmarkets.net",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: "Official fee schedule",
      url: "https://www.btcmarkets.net/fees",
      sourceType: ProviderSourceType.OFFICIAL_FEES,
    },
    {
      label: "Official regulation information",
      url: "https://www.btcmarkets.net/regulation",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
  ],
  regulations: [
    {
      jurisdiction: "AU",
      regulator: "AUSTRAC",
      status:
        "Registered with AUSTRAC as a virtual asset service provider; BTC Markets also describes itself as a registered Digital Currency Exchange",
      sourceUrl: "https://www.btcmarkets.net/regulation",
      verifiedAt: new Date("2026-09-17"),
    },
  ],
};
