import {
  FeeValueType,
  ProviderFeatureType,
  ProviderFeeType,
  ProviderProsConsType,
  ProviderSourceType,
  ProviderType,
  VerificationStatus,
} from "@prisma/client";

export const CoinSpot = {
  name: "CoinSpot",
  slug: "coinspot",
  website: "https://www.coinspot.com.au",
  description:
    "Australian cryptocurrency platform offering Instant Buy/Sell/Swap, Markets and OTC trading, with AUD funding including PayID and Direct Deposit.",
  providerType: ProviderType.CRYPTO_EXCHANGE,
  jurisdictions: ["AU"],
  verificationStatus: VerificationStatus.VERIFIED,
  lastVerifiedAt: new Date("2026-09-17"),
  assetSymbols: ["BTC", "ETH", "SOL"],
  logo: "/images/providers/coinspot.svg",
  facts: [
    {
      label: "Headquarters / Market",
      value: "Australia",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "AUD Support",
      value: "Yes",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Platform Type",
      value:
        "Centralised cryptocurrency platform with instant trading, Markets and OTC",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Operating entity",
      value:
        "Casey Block Services Pty Ltd (ACN 619 574 186), trading as CoinSpot",
      jurisdiction: "AU",
      sourceUrl:
        "https://www.coinspot.com.au/public/CoinSpot%20Mastercard%20FSG.pdf?v=410",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  fees: [
    {
      feeType: ProviderFeeType.TRADING,
      label: "Markets order-book fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 0.1,
      displayValue: "0.1%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.INSTANT_BUY,
      label: "Instant Buy / Sell / Swap fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 1.0,
      displayValue: "1%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.OTHER,
      label: "OTC desk fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 0.1,
      displayValue: "0.1%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: "AUD PayID / Direct Deposit fee",
      valueType: FeeValueType.FREE,
      displayValue: "Free",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: "AUD card deposit fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 1.22,
      displayValue: "1.22%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.WITHDRAWAL,
      label: "Crypto withdrawal fee",
      valueType: FeeValueType.VARIABLE,
      displayValue:
        "A flat transaction/mining fee applies; current amount is shown on the relevant wallet page",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  features: [
    {
      featureType: ProviderFeatureType.AUD_DEPOSITS,
      available: true,
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.AUD_WITHDRAWALS,
      available: true,
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.PAYID,
      available: true,
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.BANK_TRANSFER,
      available: true,
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.RECURRING_BUYS,
      available: true,
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.OTC_DESK,
      available: true,
      sourceUrl: "https://www.coinspot.com.au/otc",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  prosCons: [
    {
      type: ProviderProsConsType.PRO,
      label: "Markets and OTC trading are priced at 0.1%",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.PRO,
      label:
        "PayID and Direct Deposit are fee-free and AUD bank withdrawals are free",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label:
        "Instant Buy/Sell/Swap costs 1%, compared with 0.1% for Markets orders",
      sourceUrl: "https://www.coinspot.com.au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],
  sources: [
    {
      label: "Official website",
      url: "https://www.coinspot.com.au",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: "Official fees",
      url: "https://www.coinspot.com.au/fees",
      sourceType: ProviderSourceType.OFFICIAL_FEES,
    },
    {
      label: "Official Financial Services Guide",
      url: "https://www.coinspot.com.au/public/CoinSpot%20Mastercard%20FSG.pdf?v=410",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
  ],
  regulations: [
    {
      jurisdiction: "AU",
      regulator: "AUSTRAC",
      status:
        "Registered Australian digital currency exchange / virtual asset service provider; verify current public-register wording before display",
      sourceUrl: "https://www.coinspot.com.au",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      jurisdiction: "AU",
      regulator: "ASIC",
      status:
        "Casey Block Services Pty Ltd holds AFSL 562554 for financial services described in CoinSpot's FSG; do not imply the AFSL covers all spot-crypto exchange services",
      sourceUrl:
        "https://www.coinspot.com.au/public/CoinSpot%20Mastercard%20FSG.pdf?v=410",
      verifiedAt: new Date("2026-09-17"),
    },
  ],
};
