import {
  FeeValueType,
  ProviderFeatureType,
  ProviderFeeType,
  ProviderProsConsType,
  ProviderSourceType,
  ProviderType,
  VerificationStatus,
} from "@prisma/client";

export const CoinJar = {
  name: "CoinJar",
  slug: "coinjar",
  website: "https://www.coinjar.com/au",
  logo: "/images/providers/coinjar.svg",

  description:
    "Australian cryptocurrency exchange operating since 2013, offering a simple buy/sell experience alongside CoinJar Exchange for active trading, with AUD funding, 60+ digital assets, recurring buys, Bundles, SMSF accounts, OTC services and a mobile app.",

  providerType: ProviderType.CRYPTO_EXCHANGE,
  jurisdictions: ["AU"],
  verificationStatus: VerificationStatus.VERIFIED,
  lastVerifiedAt: new Date("2026-09-17"),

  assetSymbols: ["BTC", "ETH", "SOL", "XRP"],

  facts: [
    {
      label: "Operating entity",
      value: "CoinJar Australia Pty Ltd (ACN 648 570 807)",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/legal",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Headquarters / Market",
      value: "Australia",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/about-us",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Founded",
      value: "2013",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/about-us",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "AUD Support",
      value: "Yes",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Platform Type",
      value:
        "Centralised cryptocurrency exchange with retail app and CoinJar Exchange order-book trading",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/exchange",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Advertised crypto assets",
      value: "60+",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/about-us",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "Customers",
      value: "800,000+",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/about-us",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      label: "CoinJar Exchange markets",
      value: "380+ AUD, USD, GBP and BTC trading pairs",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/exchange",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],

  fees: [
    {
      feeType: ProviderFeeType.INSTANT_BUY,
      label: "CoinJar fiat-to-crypto conversion fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 1,
      displayValue: "1%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.TRADING,
      label: "Crypto-to-fiat conversion fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 1,
      displayValue: "1%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.TRADING,
      label: "Crypto-to-crypto conversion fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 1,
      displayValue: "1%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.MAKER,
      label: "CoinJar Exchange fiat-pair maker fee",
      valueType: FeeValueType.TIERED,
      percentage: 0.1,
      displayValue:
        "0.10% at the entry tier; falls to 0.02% above $10m 30-day trading volume",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.TAKER,
      label: "CoinJar Exchange fiat-pair taker fee",
      valueType: FeeValueType.TIERED,
      percentage: 0.1,
      displayValue:
        "0.10% at the entry tier; falls to 0.06% above $10m 30-day trading volume",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.MAKER,
      label: "Crypto-to-crypto / crypto-to-stablecoin maker fee",
      valueType: FeeValueType.FREE,
      percentage: 0,
      displayValue: "0%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.TAKER,
      label: "Crypto-to-crypto / crypto-to-stablecoin taker fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 0.06,
      displayValue: "0.06%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: "AUD PayID / Osko / NPP deposit fee",
      valueType: FeeValueType.FREE,
      displayValue: "Free",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: "AUD bank transfer deposit fee",
      valueType: FeeValueType.FREE,
      displayValue: "Free",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_WITHDRAWAL,
      label: "AUD bank withdrawal fee",
      valueType: FeeValueType.FREE,
      displayValue: "Free",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: "PayPal AUD deposit fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 0.5,
      displayValue: "0.5%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_WITHDRAWAL,
      label: "PayPal AUD withdrawal fee",
      valueType: FeeValueType.FREE,
      displayValue: "Free for withdrawals back to PayPal from crypto sales",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: "Visa / Mastercard crypto purchase",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 2,
      displayValue: "2%",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.OTHER,
      label: "Recurring Buy fee",
      valueType: FeeValueType.PERCENTAGE,
      percentage: 1,
      displayValue:
        "1% for recurring purchases using debit/credit card or Apple Pay / Google Pay",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      feeType: ProviderFeeType.WITHDRAWAL,
      label: "External cryptocurrency transfer fee",
      valueType: FeeValueType.VARIABLE,
      displayValue:
        "Dynamic fee that varies by cryptocurrency and network conditions",
      jurisdiction: "AU",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],

  features: [
    {
      featureType: ProviderFeatureType.AUD_DEPOSITS,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/fees",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.AUD_WITHDRAWALS,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/fees",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.PAYID,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/fees",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.BANK_TRANSFER,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/fees",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.CARD_DEPOSIT,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/instant-buy",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.MOBILE_APP,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/app",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.RECURRING_BUYS,
      available: true,
      label: "Recurring Buy (weekly, fortnightly or monthly)",
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/recurring-buy",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.API_ACCESS,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/exchange",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.ADVANCED_CHARTING,
      available: true,
      label: "TradingView integration",
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/exchange",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.OTC_DESK,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/otc-trading-desk",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.SMSF_SUPPORT,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/smsf",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.COLD_STORAGE,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/security",
      verifiedAt: new Date("2026-09-17"),
    },
    {
      featureType: ProviderFeatureType.TWO_FACTOR_AUTH,
      available: true,
      verificationStatus: VerificationStatus.VERIFIED,
      sourceUrl: "https://www.coinjar.com/au/security",
      verifiedAt: new Date("2026-09-17"),
    },
  ],

  prosCons: [
    {
      type: ProviderProsConsType.PRO,
      label:
        "CoinJar Exchange starts at 0.10% maker/taker for fiat pairs, with lower rates at higher trading volumes",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.PRO,
      label:
        "Free AUD deposits through PayID/Osko/NPP and bank transfer, with free standard AUD bank withdrawals",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.PRO,
      label:
        "Supports retail buying, advanced exchange trading, recurring buys, Bundles, SMSF accounts and OTC trading",
      sourceUrl: "https://www.coinjar.com/au",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.PRO,
      label:
        "CoinJar says the vast majority of assets are held in cold storage or private multi-signature wallets",
      sourceUrl: "https://www.coinjar.com/au/security",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label:
        "Simple CoinJar conversions cost 1%, substantially more than the entry-level 0.10% CoinJar Exchange fee",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label:
        "Card purchases cost 2%, while PayID and standard bank-transfer funding are fee-free",
      sourceUrl: "https://www.coinjar.com/au/fees",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label:
        "CoinJar may include a spread in quoted cryptocurrency prices in addition to applicable transaction fees",
      sourceUrl: "https://www.coinjar.com/au/legal",
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date("2026-09-17"),
    },
  ],

  sources: [
    {
      label: "Official website",
      url: "https://www.coinjar.com/au",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: "Official fees",
      url: "https://www.coinjar.com/au/fees",
      sourceType: ProviderSourceType.OFFICIAL_FEES,
    },
    {
      label: "Official Australian Terms of Service",
      url: "https://www.coinjar.com/au/legal",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: "Official security information",
      url: "https://www.coinjar.com/au/security",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: "Official CoinJar Exchange",
      url: "https://www.coinjar.com/au/exchange",
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: "Official AUSTRAC regulatory information",
      url: "https://support.coinjar.com/hc/en-au/articles/28814873312793-CoinJar-s-regulatory-obligations",
      sourceType: ProviderSourceType.OFFICIAL_SUPPORT,
    },
  ],

  regulations: [
    {
      jurisdiction: "AU",
      regulator: "AUSTRAC",
      status:
        "CoinJar Australia Pty Ltd is a registered Virtual Asset Service Provider (VASP) with AUSTRAC",
      sourceUrl: "https://www.coinjar.com/au/legal",
      verifiedAt: new Date("2026-09-17"),
    },
  ],
};
