import {
  FeeValueType,
  ProviderFeatureType,
  ProviderFeeType,
  ProviderProsConsType,
  ProviderSourceType,
  ProviderType,
  VerificationStatus,
} from '@prisma/client';

export const IndependentReserve = {
  name: 'Independent Reserve',
  slug: 'independent-reserve',
  website: 'https://www.independentreserve.com',
  logo: '/images/providers/independent-reserve.svg',
  description:
    'Australian cryptocurrency exchange established in 2013, offering transparent order-book trading, recurring buys, API access, OTC trading and SMSF/business account support.',
  providerType: ProviderType.CRYPTO_EXCHANGE,
  jurisdictions: ['AU'],
  verificationStatus: VerificationStatus.VERIFIED,
  lastVerifiedAt: new Date('2026-09-17'),
  assetSymbols: ['BTC', 'ETH', 'SOL', 'XRP'],
  facts: [
    {
      label: 'Headquarters / Market',
      value: 'Australia',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      label: 'Platform Type',
      value: 'Centralised cryptocurrency exchange with transparent order book',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      label: 'Founded',
      value: '2013',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      label: 'Ownership',
      value:
        'IG Group completed its acquisition of Independent Reserve effective 30 January 2026',
      jurisdiction: 'AU',
      sourceUrl:
        'https://www.independentreserve.com/blog/news/announcement-ig-group-completes-acquisition-of-independent-reserve',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
  ],
  fees: [
    {
      feeType: ProviderFeeType.TRADING,
      label: 'Trading fee',
      valueType: FeeValueType.TIERED,
      percentage: 0.5,
      displayValue:
        '0.50% starting fee, tiered down to 0.02% at AUD $200m rolling 30-day trading volume',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      feeType: ProviderFeeType.FIAT_DEPOSIT,
      label: 'AUD bank transfer deposit',
      valueType: FeeValueType.FREE,
      displayValue: 'Free',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      feeType: ProviderFeeType.FIAT_WITHDRAWAL,
      label: 'AUD EFT withdrawal',
      valueType: FeeValueType.FREE,
      displayValue: 'Free',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      feeType: ProviderFeeType.FIAT_WITHDRAWAL,
      label: 'AUD PayID/NPP instant withdrawal',
      valueType: FeeValueType.FIXED,
      fixedAmount: 1.5,
      currency: 'AUD',
      displayValue: 'AUD 1.50',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      feeType: ProviderFeeType.WITHDRAWAL,
      label: 'Bitcoin withdrawal',
      valueType: FeeValueType.FIXED,
      fixedAmount: 0.0001,
      currency: 'BTC',
      displayValue: '0.0001 BTC',
      jurisdiction: 'AU',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
  ],
  features: [
    {
      featureType: ProviderFeatureType.AUD_DEPOSITS,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.BANK_TRANSFER,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.API_ACCESS,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.SMSF_SUPPORT,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au/features/smsf',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.MOBILE_APP,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au/features/mobile-app',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.RECURRING_BUYS,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.OTC_DESK,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.COLD_STORAGE,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au/features/smsf',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      featureType: ProviderFeatureType.TWO_FACTOR_AUTH,
      available: true,
      sourceUrl: 'https://www.independentreserve.com/au/features/mobile-app',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
  ],
  prosCons: [
    {
      type: ProviderProsConsType.PRO,
      label:
        'Trading fee decreases from 0.50% to 0.02% as rolling 30-day trading volume increases',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      type: ProviderProsConsType.PRO,
      label: 'AUD bank-transfer deposits and AUD EFT withdrawals are free',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
    {
      type: ProviderProsConsType.LIMITATION,
      label: 'The starting trading fee is 0.50% before volume discounts',
      sourceUrl: 'https://www.independentreserve.com/au/fees',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date('2026-09-17'),
    },
  ],
  sources: [
    {
      label: 'Official website',
      url: 'https://www.independentreserve.com/au',
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
    {
      label: 'Official fee schedule',
      url: 'https://www.independentreserve.com/au/fees',
      sourceType: ProviderSourceType.OFFICIAL_FEES,
    },
    {
      label: 'Official acquisition announcement',
      url: 'https://www.independentreserve.com/blog/news/announcement-ig-group-completes-acquisition-of-independent-reserve',
      sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
    },
  ],
  regulations: [
    {
      jurisdiction: 'AU',
      regulator: 'AUSTRAC',
      status:
        'Registered Digital Currency Exchange (DCE), registration DCE-100461150-001',
      sourceUrl: 'https://www.independentreserve.com/au',
      verifiedAt: new Date('2026-09-17'),
    },
  ],
};
