import {
  FeeCalculationBasis,
  FeeCategory,
  OfferingFeatureType,
  OfferingProsConsType,
  OfferingType,
  ProviderSourceType,
  VerificationStatus,
} from "@prisma/client";

export const CoinJar = {
  provider: {
    name: "CoinJar",
    slug: "coinjar",
    website: "https://www.coinjar.com/au",
    logo: "/images/providers/coinjar.svg",

    description:
      "Australian cryptocurrency exchange operating since 2013, offering a simple buy/sell experience alongside CoinJar Exchange for active trading, with AUD funding, 60+ digital assets, recurring buys, Bundles, SMSF accounts, OTC services and a mobile app.",

    jurisdictions: ["AU"],
    verificationStatus: VerificationStatus.VERIFIED,
    lastVerifiedAt: new Date("2026-09-17"),
    facts: [
      {
        label: "Operating entity",
        value: "CoinJar Australia Pty Ltd (ACN 648 570 807)",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/legal",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Headquarters / Market",
        value: "Australia",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/about-us",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Founded",
        value: "2013",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/about-us",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Platform Type",
        value:
          "Centralised cryptocurrency exchange with retail app and CoinJar Exchange order-book trading",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/exchange",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Advertised crypto assets",
        value: "60+",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/about-us",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Customers",
        value: "800,000+",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/about-us",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "CoinJar Exchange markets",
        value: "380+ AUD, USD, GBP and BTC trading pairs",
        jurisdiction: "AU",
        sourceUrl: "https://www.coinjar.com/au/exchange",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
    sources: [
      {
        label: "Official website",
        url: "https://www.coinjar.com/au",
        sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
      },
      {
        label: "Official fees",
        url: "https://www.coinjar.com/au/fees",
        sourceType: ProviderSourceType.OFFICIAL_FEES,
      },
      {
        label: "Official Australian Terms of Service",
        url: "https://www.coinjar.com/au/legal",
        sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
      },
      {
        label: "Official security information",
        url: "https://www.coinjar.com/au/security",
        sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
      },
      {
        label: "Official CoinJar Exchange",
        url: "https://www.coinjar.com/au/exchange",
        sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
      },
      {
        label: "Official AUSTRAC regulatory information",
        url: "https://support.coinjar.com/hc/en-au/articles/28814873312793-CoinJar-s-regulatory-obligations",
        sourceType: ProviderSourceType.OFFICIAL_SUPPORT,
      },
    ],
    regulations: [
      {
        jurisdiction: "AU",
        regulator: "AUSTRAC",
        status:
          "CoinJar Australia Pty Ltd is a registered Virtual Asset Service Provider (VASP) with AUSTRAC",
        sourceUrl: "https://www.coinjar.com/au/legal",
        verifiedAt: new Date("2026-09-17"),
      },
    ],
  },
  offering: {
    name: "CoinJar Crypto Exchange",
    slug: "coinjar-exchange",
    offeringType: OfferingType.CRYPTO_EXCHANGE,
    jurisdiction: "AU",
    assetSymbols: ["BTC", "ETH", "SOL", "XRP"],
    fees: [
      {
        feeCategory: FeeCategory.INSTANT_BUY,
        label: "CoinJar fiat-to-crypto conversion fee",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 1,
        displayValue: "1%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.CRYPTO_TRADING,
        label: "Crypto-to-fiat conversion fee",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 1,
        displayValue: "1%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.CRYPTO_TRADING,
        label: "Crypto-to-crypto conversion fee",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 1,
        displayValue: "1%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.MAKER,
        label: "CoinJar Exchange fiat-pair maker fee",
        calculationBasis: FeeCalculationBasis.TIERED,
        percentage: 0.1,
        currency: "AUD",
        tierVolumeCurrency: "AUD",
        tiers: [
          { minAmount: 0, minRolling30DayVolume: 0, percentage: 0.1 },
          { minAmount: 0, minRolling30DayVolume: 100000, percentage: 0.08 },
          { minAmount: 0, minRolling30DayVolume: 1000000, percentage: 0.04 },
          { minAmount: 0, minRolling30DayVolume: 10000000, percentage: 0.02 },
        ],
        displayValue:
          "0.10% at the entry tier; falls to 0.02% above $10m 30-day trading volume",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.TAKER,
        label: "CoinJar Exchange fiat-pair taker fee",
        calculationBasis: FeeCalculationBasis.TIERED,
        percentage: 0.1,
        currency: "AUD",
        tierVolumeCurrency: "AUD",
        tiers: [
          { minAmount: 0, minRolling30DayVolume: 0, percentage: 0.1 },
          { minAmount: 0, minRolling30DayVolume: 100000, percentage: 0.1 },
          { minAmount: 0, minRolling30DayVolume: 1000000, percentage: 0.08 },
          { minAmount: 0, minRolling30DayVolume: 10000000, percentage: 0.06 },
        ],
        displayValue:
          "0.10% at the entry tier; falls to 0.06% above $10m 30-day trading volume",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.MAKER,
        label: "Crypto-to-crypto / crypto-to-stablecoin maker fee",
        calculationBasis: FeeCalculationBasis.FREE,
        percentage: 0,
        displayValue: "0%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.TAKER,
        label: "Crypto-to-crypto / crypto-to-stablecoin taker fee",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 0.06,
        displayValue: "0.06%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_DEPOSIT,
        label: "AUD PayID / Osko / NPP deposit fee",
        calculationBasis: FeeCalculationBasis.FREE,
        displayValue: "Free",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_DEPOSIT,
        label: "AUD bank transfer deposit fee",
        calculationBasis: FeeCalculationBasis.FREE,
        displayValue: "Free",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_WITHDRAWAL,
        label: "AUD bank withdrawal fee",
        calculationBasis: FeeCalculationBasis.FREE,
        displayValue: "Free",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_DEPOSIT,
        label: "PayPal AUD deposit fee",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 0.5,
        displayValue: "0.5%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_WITHDRAWAL,
        label: "PayPal AUD withdrawal fee",
        calculationBasis: FeeCalculationBasis.FREE,
        displayValue: "Free for withdrawals back to PayPal from crypto sales",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_DEPOSIT,
        label: "Visa / Mastercard crypto purchase",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 2,
        displayValue: "2%",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.OTHER,
        label: "Recurring Buy fee",
        calculationBasis: FeeCalculationBasis.PERCENTAGE,
        percentage: 1,
        displayValue:
          "1% for recurring purchases using debit/credit card or Apple Pay / Google Pay",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.CRYPTO_WITHDRAWAL,
        label: "External cryptocurrency transfer fee",
        calculationBasis: FeeCalculationBasis.VARIES,
        displayValue:
          "Dynamic fee that varies by cryptocurrency and network conditions",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
    features: [
      {
        featureType: OfferingFeatureType.AUD_DEPOSITS,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/fees",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.AUD_WITHDRAWALS,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/fees",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.PAYID,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/fees",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.BANK_TRANSFER,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/fees",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.CARD_DEPOSIT,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/instant-buy",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.MOBILE_APP,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/app",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.RECURRING_BUYS,
        available: true,
        label: "Recurring Buy (weekly, fortnightly or monthly)",
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/recurring-buy",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.API_ACCESS,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/exchange",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.ADVANCED_CHARTING,
        available: true,
        label: "TradingView integration",
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/exchange",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.OTC_DESK,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/otc-trading-desk",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.SMSF_SUPPORT,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/smsf",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.COLD_STORAGE,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/security",
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.TWO_FACTOR_AUTH,
        available: true,
        verificationStatus: VerificationStatus.VERIFIED,
        sourceUrl: "https://www.coinjar.com/au/security",
        verifiedAt: new Date("2026-09-17"),
      },
    ],
    prosCons: [
      {
        type: OfferingProsConsType.PRO,
        label:
          "CoinJar Exchange starts at 0.10% maker/taker for fiat pairs, with lower rates at higher trading volumes",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.PRO,
        label:
          "Free AUD deposits through PayID/Osko/NPP and bank transfer, with free standard AUD bank withdrawals",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.PRO,
        label:
          "Supports retail buying, advanced exchange trading, recurring buys, Bundles, SMSF accounts and OTC trading",
        sourceUrl: "https://www.coinjar.com/au",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.PRO,
        label:
          "CoinJar says the vast majority of assets are held in cold storage or private multi-signature wallets",
        sourceUrl: "https://www.coinjar.com/au/security",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.LIMITATION,
        label:
          "Simple CoinJar conversions cost 1%, substantially more than the entry-level 0.10% CoinJar Exchange fee",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.LIMITATION,
        label:
          "Card purchases cost 2%, while PayID and standard bank-transfer funding are fee-free",
        sourceUrl: "https://www.coinjar.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.LIMITATION,
        label:
          "CoinJar may include a spread in quoted cryptocurrency prices in addition to applicable transaction fees",
        sourceUrl: "https://www.coinjar.com/au/legal",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
  },
};
