import {
  FeeCalculationBasis,
  FeeCategory,
  OfferingFeatureType,
  OfferingProsConsType,
  OfferingType,
  ProviderSourceType,
  VerificationStatus,
} from "@prisma/client";

export const IndependentReserve = {
  provider: {
    name: "Independent Reserve",
    slug: "independent-reserve",
    website: "https://www.independentreserve.com",
    logo: "/images/providers/independent-reserve.svg",
    description:
      "Australian cryptocurrency exchange established in 2013, offering transparent order-book trading, recurring buys, API access, OTC trading and SMSF/business account support.",
    jurisdictions: ["AU"],
    verificationStatus: VerificationStatus.VERIFIED,
    lastVerifiedAt: new Date("2026-09-17"),
    facts: [
      {
        label: "Headquarters / Market",
        value: "Australia",
        jurisdiction: "AU",
        sourceUrl: "https://www.independentreserve.com/au",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Platform Type",
        value:
          "Centralised cryptocurrency exchange with transparent order book",
        jurisdiction: "AU",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Founded",
        value: "2013",
        jurisdiction: "AU",
        sourceUrl: "https://www.independentreserve.com/au",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        label: "Ownership",
        value:
          "IG Group completed its acquisition of Independent Reserve effective 30 January 2026",
        jurisdiction: "AU",
        sourceUrl:
          "https://www.independentreserve.com/blog/news/announcement-ig-group-completes-acquisition-of-independent-reserve",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
    sources: [
      {
        label: "Official website",
        url: "https://www.independentreserve.com/au",
        sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
      },
      {
        label: "Official fee schedule",
        url: "https://www.independentreserve.com/au/fees",
        sourceType: ProviderSourceType.OFFICIAL_FEES,
      },
      {
        label: "Official acquisition announcement",
        url: "https://www.independentreserve.com/blog/news/announcement-ig-group-completes-acquisition-of-independent-reserve",
        sourceType: ProviderSourceType.OFFICIAL_WEBSITE,
      },
    ],
    regulations: [
      {
        jurisdiction: "AU",
        regulator: "AUSTRAC",
        status:
          "Registered Digital Currency Exchange (DCE), registration DCE-100461150-001",
        sourceUrl: "https://www.independentreserve.com/au",
        verifiedAt: new Date("2026-09-17"),
      },
    ],
  },
  offering: {
    name: "Independent Reserve Crypto Exchange",
    slug: "independent-reserve-exchange",
    offeringType: OfferingType.CRYPTO_EXCHANGE,
    jurisdiction: "AU",
    assetSymbols: ["BTC", "ETH", "SOL", "XRP"],
    fees: [
      {
        feeCategory: FeeCategory.CRYPTO_TRADING,
        label: "Trading fee",
        calculationBasis: FeeCalculationBasis.TIERED,
        percentage: 0.5,
        displayValue:
          "0.50% starting fee, tiered down to 0.02% at AUD $200m rolling 30-day trading volume",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_DEPOSIT,
        label: "AUD bank transfer deposit",
        calculationBasis: FeeCalculationBasis.FREE,
        displayValue: "Free",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_WITHDRAWAL,
        label: "AUD EFT withdrawal",
        calculationBasis: FeeCalculationBasis.FREE,
        displayValue: "Free",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.FIAT_WITHDRAWAL,
        label: "AUD PayID/NPP instant withdrawal",
        calculationBasis: FeeCalculationBasis.FLAT,
        flatAmount: 1.5,
        currency: "AUD",
        displayValue: "AUD 1.50",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        feeCategory: FeeCategory.CRYPTO_WITHDRAWAL,
        label: "Bitcoin withdrawal",
        calculationBasis: FeeCalculationBasis.FLAT,
        flatAmount: 0.0001,
        currency: "BTC",
        displayValue: "0.0001 BTC",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
    features: [
      {
        featureType: OfferingFeatureType.AUD_DEPOSITS,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.BANK_TRANSFER,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.API_ACCESS,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.SMSF_SUPPORT,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au/features/smsf",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.MOBILE_APP,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au/features/mobile-app",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.RECURRING_BUYS,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.OTC_DESK,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.COLD_STORAGE,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au/features/smsf",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        featureType: OfferingFeatureType.TWO_FACTOR_AUTH,
        available: true,
        sourceUrl: "https://www.independentreserve.com/au/features/mobile-app",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
    prosCons: [
      {
        type: OfferingProsConsType.PRO,
        label:
          "Trading fee decreases from 0.50% to 0.02% as rolling 30-day trading volume increases",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.PRO,
        label: "AUD bank-transfer deposits and AUD EFT withdrawals are free",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
      {
        type: OfferingProsConsType.LIMITATION,
        label: "The starting trading fee is 0.50% before volume discounts",
        sourceUrl: "https://www.independentreserve.com/au/fees",
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: new Date("2026-09-17"),
      },
    ],
  },
};
